name: Deploy static content to Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/checkout@v3
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.8.0
          registry-url: https://registry.npmjs.org/
      - name: install
        run: npm install
      - name: build
        run: |
          npm run clean
          npm run build
      - name: setup GitHub Pages
        uses: actions/configure-pages@v3
      - name: prepare artifact
        run: |
          mkdir -p _site
          cp -r demo _site/demo
          cp -r dist _site/dist
      - name: upload artifact
        uses: actions/upload-pages-artifact@v1
      - name: deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1
